# Generated by Django 4.0.2 on 2022-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='ticket',
        ),
        migrations.AddField(
            model_name='screening',
            name='ticket',
            field=models.ManyToManyField(to='movieTheater.Ticket'),
        ),
    ]
