# Generated by Django 4.0.2 on 2022-06-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0003_ticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieTheater.ticket'),
        ),
    ]
