# Generated by Django 4.0.2 on 2022-06-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0008_remove_ticket_seat_booking_seat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='TicketType',
        ),
    ]
