# Generated by Django 4.0.2 on 2022-06-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0009_rename_ticket_tickettype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ticket',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='ticket',
            new_name='ticket_type',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='ticket',
            new_name='ticket_type',
        ),
    ]
