# Generated by Django 4.0.2 on 2022-07-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0012_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='movie_title',
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
