# Generated by Django 4.0.2 on 2022-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieTheater', '0013_booking_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screen_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='screen_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seatCode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
